version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqlcontainer
    environment:
      MYSQL_DATABASE: db_banque_lsi
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Allow empty password (for local dev purposes)
    networks:
      - networkmysql
    ports:
      - "3307:3306"  # Expose MySQL on port 3307 locally
    restart: always  # Ensures the MySQL container restarts if it stops or crashes

  bankapp:
    image: abakhar217/abakhar0:bankapp
    container_name: bankcontainer
    environment:
      MYSQL_HOST: mysqlcontainer  # Reference to MySQL container
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: db_banque_lsi  # Just the database name
      MYSQL_ROOT: root  # Assuming MySQL root is used, even with no password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Same as above
    ports:
      - "8090:8080"  # Expose your app on port 8090 locally
    networks:
      - networkmysql
    depends_on:
      - mysql  # Ensure MySQL is started before the bankapp
    command: ["dockerize", "-wait", "tcp://mysqlcontainer:3306", "-timeout", "60s", "java", "-jar", "bankapp.jar"]
    restart: always  # Ensures the Bank app container restarts if it stops or crashes

networks:
  networkmysql:
    driver: bridge
