version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_banque_lsi
    networks:
      - networkmysql
    ports:
      - "3307:3306"

  bankapp:
    image: abakhar217/abakhar0:bankapp
    container_name: bankcontainer
    environment:
      MYSQL_HOST: mysqlcontainer
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: db_banque_lsi
      MYSQL_USER: root
      MYSQL_PASSWORD:""
    ports:
      - "8090:8080"
    networks:
      - networkmysql
    depends_on:
      - mysql

networks:
  networkmysql:
    driver: bridge
